/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ClienteRouteImport } from './routes/_cliente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CondizioniGeneraliRouteImport } from './routes/condizioni-generali'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DoveSiamoRouteImport } from './routes/dove-siamo'
import { Route as FlottaRouteImport } from './routes/flotta'
import { Route as PrenotaRouteImport } from './routes/prenota'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TerminiECondizioniRouteImport } from './routes/termini-e-condizioni'
import { Route as VeicoliCommercialiRouteImport } from './routes/veicoli-commerciali'
import { Route as AuthenticatedGestionaleRouteImport } from './routes/_authenticated/gestionale'
import { Route as AreaClientiAccediRouteImport } from './routes/area-clienti.accedi'
import { Route as AuthenticatedGestionaleIndexRouteImport } from './routes/_authenticated/gestionale.index'
import { Route as AuthenticatedGestionaleAnalyticsRouteImport } from './routes/_authenticated/gestionale.analytics'
import { Route as AuthenticatedGestionaleCalendarioRouteImport } from './routes/_authenticated/gestionale.calendario'
import { Route as AuthenticatedGestionaleCargosRouteImport } from './routes/_authenticated/gestionale.cargos'
import { Route as AuthenticatedGestionaleClientiRouteImport } from './routes/_authenticated/gestionale.clienti'
import { Route as AuthenticatedGestionaleDocumentiLegaliRouteImport } from './routes/_authenticated/gestionale.documenti-legali'
import { Route as AuthenticatedGestionaleFattureRouteImport } from './routes/_authenticated/gestionale.fatture'
import { Route as AuthenticatedGestionalePartnerRouteImport } from './routes/_authenticated/gestionale.partner'
import { Route as AuthenticatedGestionalePrenotazioniRouteImport } from './routes/_authenticated/gestionale.prenotazioni'
import { Route as AuthenticatedGestionaleTariffeRouteImport } from './routes/_authenticated/gestionale.tariffe'
import { Route as AuthenticatedGestionaleUtentiRouteImport } from './routes/_authenticated/gestionale.utenti'
import { Route as AuthenticatedGestionaleVerbaliRouteImport } from './routes/_authenticated/gestionale.verbali'
import { Route as ClienteAreaClientiIndexRouteImport } from './routes/_cliente.area-clienti.index'
import { Route as AuthenticatedGestionaleVeicoliIndexRouteImport } from './routes/_authenticated/gestionale.veicoli.index'
import { Route as AuthenticatedGestionaleVeicoliVehicleIdRouteImport } from './routes/_authenticated/gestionale.veicoli.$vehicleId'
import { Route as ApiPublicCronCargosRouteImport } from './routes/api/public/cron/cargos'
import { Route as ApiPublicCronNotificationsRouteImport } from './routes/api/public/cron/notifications'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/_cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CondizioniGeneraliRoute = CondizioniGeneraliRouteImport.update({
  id: '/condizioni-generali',
  path: '/condizioni-generali',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DoveSiamoRoute = DoveSiamoRouteImport.update({
  id: '/dove-siamo',
  path: '/dove-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const FlottaRoute = FlottaRouteImport.update({
  id: '/flotta',
  path: '/flotta',
  getParentRoute: () => rootRouteImport,
} as any)
const PrenotaRoute = PrenotaRouteImport.update({
  id: '/prenota',
  path: '/prenota',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminiECondizioniRoute = TerminiECondizioniRouteImport.update({
  id: '/termini-e-condizioni',
  path: '/termini-e-condizioni',
  getParentRoute: () => rootRouteImport,
} as any)
const VeicoliCommercialiRoute = VeicoliCommercialiRouteImport.update({
  id: '/veicoli-commerciali',
  path: '/veicoli-commerciali',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGestionaleRoute = AuthenticatedGestionaleRouteImport.update({
  id: '/gestionale',
  path: '/gestionale',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AreaClientiAccediRoute = AreaClientiAccediRouteImport.update({
  id: '/area-clienti/accedi',
  path: '/area-clienti/accedi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGestionaleIndexRoute =
  AuthenticatedGestionaleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleAnalyticsRoute =
  AuthenticatedGestionaleAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleCalendarioRoute =
  AuthenticatedGestionaleCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleCargosRoute =
  AuthenticatedGestionaleCargosRouteImport.update({
    id: '/cargos',
    path: '/cargos',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleClientiRoute =
  AuthenticatedGestionaleClientiRouteImport.update({
    id: '/clienti',
    path: '/clienti',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleDocumentiLegaliRoute =
  AuthenticatedGestionaleDocumentiLegaliRouteImport.update({
    id: '/documenti-legali',
    path: '/documenti-legali',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleFattureRoute =
  AuthenticatedGestionaleFattureRouteImport.update({
    id: '/fatture',
    path: '/fatture',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionalePartnerRoute =
  AuthenticatedGestionalePartnerRouteImport.update({
    id: '/partner',
    path: '/partner',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionalePrenotazioniRoute =
  AuthenticatedGestionalePrenotazioniRouteImport.update({
    id: '/prenotazioni',
    path: '/prenotazioni',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleTariffeRoute =
  AuthenticatedGestionaleTariffeRouteImport.update({
    id: '/tariffe',
    path: '/tariffe',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleUtentiRoute =
  AuthenticatedGestionaleUtentiRouteImport.update({
    id: '/utenti',
    path: '/utenti',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleVerbaliRoute =
  AuthenticatedGestionaleVerbaliRouteImport.update({
    id: '/verbali',
    path: '/verbali',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const ClienteAreaClientiIndexRoute = ClienteAreaClientiIndexRouteImport.update({
  id: '/area-clienti/',
  path: '/area-clienti/',
  getParentRoute: () => ClienteRoute,
} as any)
const AuthenticatedGestionaleVeicoliIndexRoute =
  AuthenticatedGestionaleVeicoliIndexRouteImport.update({
    id: '/veicoli/',
    path: '/veicoli/',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleVeicoliVehicleIdRoute =
  AuthenticatedGestionaleVeicoliVehicleIdRouteImport.update({
    id: '/veicoli/$vehicleId',
    path: '/veicoli/$vehicleId',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const ApiPublicCronCargosRoute = ApiPublicCronCargosRouteImport.update({
  id: '/api/public/cron/cargos',
  path: '/api/public/cron/cargos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNotificationsRoute =
  ApiPublicCronNotificationsRouteImport.update({
    id: '/api/public/cron/notifications',
    path: '/api/public/cron/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/condizioni-generali': typeof CondizioniGeneraliRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dove-siamo': typeof DoveSiamoRoute
  '/flotta': typeof FlottaRoute
  '/prenota': typeof PrenotaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/termini-e-condizioni': typeof TerminiECondizioniRoute
  '/veicoli-commerciali': typeof VeicoliCommercialiRoute
  '/gestionale': typeof AuthenticatedGestionaleRouteWithChildren
  '/area-clienti/accedi': typeof AreaClientiAccediRoute
  '/gestionale/analytics': typeof AuthenticatedGestionaleAnalyticsRoute
  '/gestionale/calendario': typeof AuthenticatedGestionaleCalendarioRoute
  '/gestionale/cargos': typeof AuthenticatedGestionaleCargosRoute
  '/gestionale/clienti': typeof AuthenticatedGestionaleClientiRoute
  '/gestionale/documenti-legali': typeof AuthenticatedGestionaleDocumentiLegaliRoute
  '/gestionale/fatture': typeof AuthenticatedGestionaleFattureRoute
  '/gestionale/partner': typeof AuthenticatedGestionalePartnerRoute
  '/gestionale/prenotazioni': typeof AuthenticatedGestionalePrenotazioniRoute
  '/gestionale/tariffe': typeof AuthenticatedGestionaleTariffeRoute
  '/gestionale/utenti': typeof AuthenticatedGestionaleUtentiRoute
  '/gestionale/verbali': typeof AuthenticatedGestionaleVerbaliRoute
  '/gestionale/': typeof AuthenticatedGestionaleIndexRoute
  '/area-clienti/': typeof ClienteAreaClientiIndexRoute
  '/gestionale/veicoli/$vehicleId': typeof AuthenticatedGestionaleVeicoliVehicleIdRoute
  '/api/public/cron/cargos': typeof ApiPublicCronCargosRoute
  '/api/public/cron/notifications': typeof ApiPublicCronNotificationsRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/gestionale/veicoli/': typeof AuthenticatedGestionaleVeicoliIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/condizioni-generali': typeof CondizioniGeneraliRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dove-siamo': typeof DoveSiamoRoute
  '/flotta': typeof FlottaRoute
  '/prenota': typeof PrenotaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/termini-e-condizioni': typeof TerminiECondizioniRoute
  '/veicoli-commerciali': typeof VeicoliCommercialiRoute
  '/area-clienti/accedi': typeof AreaClientiAccediRoute
  '/gestionale/analytics': typeof AuthenticatedGestionaleAnalyticsRoute
  '/gestionale/calendario': typeof AuthenticatedGestionaleCalendarioRoute
  '/gestionale/cargos': typeof AuthenticatedGestionaleCargosRoute
  '/gestionale/clienti': typeof AuthenticatedGestionaleClientiRoute
  '/gestionale/documenti-legali': typeof AuthenticatedGestionaleDocumentiLegaliRoute
  '/gestionale/fatture': typeof AuthenticatedGestionaleFattureRoute
  '/gestionale/partner': typeof AuthenticatedGestionalePartnerRoute
  '/gestionale/prenotazioni': typeof AuthenticatedGestionalePrenotazioniRoute
  '/gestionale/tariffe': typeof AuthenticatedGestionaleTariffeRoute
  '/gestionale/utenti': typeof AuthenticatedGestionaleUtentiRoute
  '/gestionale/verbali': typeof AuthenticatedGestionaleVerbaliRoute
  '/gestionale': typeof AuthenticatedGestionaleIndexRoute
  '/area-clienti': typeof ClienteAreaClientiIndexRoute
  '/gestionale/veicoli/$vehicleId': typeof AuthenticatedGestionaleVeicoliVehicleIdRoute
  '/api/public/cron/cargos': typeof ApiPublicCronCargosRoute
  '/api/public/cron/notifications': typeof ApiPublicCronNotificationsRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/gestionale/veicoli': typeof AuthenticatedGestionaleVeicoliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_cliente': typeof ClienteRouteWithChildren
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/condizioni-generali': typeof CondizioniGeneraliRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dove-siamo': typeof DoveSiamoRoute
  '/flotta': typeof FlottaRoute
  '/prenota': typeof PrenotaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/termini-e-condizioni': typeof TerminiECondizioniRoute
  '/veicoli-commerciali': typeof VeicoliCommercialiRoute
  '/_authenticated/gestionale': typeof AuthenticatedGestionaleRouteWithChildren
  '/area-clienti/accedi': typeof AreaClientiAccediRoute
  '/_authenticated/gestionale/analytics': typeof AuthenticatedGestionaleAnalyticsRoute
  '/_authenticated/gestionale/calendario': typeof AuthenticatedGestionaleCalendarioRoute
  '/_authenticated/gestionale/cargos': typeof AuthenticatedGestionaleCargosRoute
  '/_authenticated/gestionale/clienti': typeof AuthenticatedGestionaleClientiRoute
  '/_authenticated/gestionale/documenti-legali': typeof AuthenticatedGestionaleDocumentiLegaliRoute
  '/_authenticated/gestionale/fatture': typeof AuthenticatedGestionaleFattureRoute
  '/_authenticated/gestionale/partner': typeof AuthenticatedGestionalePartnerRoute
  '/_authenticated/gestionale/prenotazioni': typeof AuthenticatedGestionalePrenotazioniRoute
  '/_authenticated/gestionale/tariffe': typeof AuthenticatedGestionaleTariffeRoute
  '/_authenticated/gestionale/utenti': typeof AuthenticatedGestionaleUtentiRoute
  '/_authenticated/gestionale/verbali': typeof AuthenticatedGestionaleVerbaliRoute
  '/_authenticated/gestionale/': typeof AuthenticatedGestionaleIndexRoute
  '/_cliente/area-clienti/': typeof ClienteAreaClientiIndexRoute
  '/_authenticated/gestionale/veicoli/$vehicleId': typeof AuthenticatedGestionaleVeicoliVehicleIdRoute
  '/api/public/cron/cargos': typeof ApiPublicCronCargosRoute
  '/api/public/cron/notifications': typeof ApiPublicCronNotificationsRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/gestionale/veicoli/': typeof AuthenticatedGestionaleVeicoliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/business'
    | '/condizioni-generali'
    | '/contatti'
    | '/cookie-policy'
    | '/dove-siamo'
    | '/flotta'
    | '/prenota'
    | '/privacy-policy'
    | '/termini-e-condizioni'
    | '/veicoli-commerciali'
    | '/gestionale'
    | '/area-clienti/accedi'
    | '/gestionale/analytics'
    | '/gestionale/calendario'
    | '/gestionale/cargos'
    | '/gestionale/clienti'
    | '/gestionale/documenti-legali'
    | '/gestionale/fatture'
    | '/gestionale/partner'
    | '/gestionale/prenotazioni'
    | '/gestionale/tariffe'
    | '/gestionale/utenti'
    | '/gestionale/verbali'
    | '/gestionale/'
    | '/area-clienti/'
    | '/gestionale/veicoli/$vehicleId'
    | '/api/public/cron/cargos'
    | '/api/public/cron/notifications'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/gestionale/veicoli/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/business'
    | '/condizioni-generali'
    | '/contatti'
    | '/cookie-policy'
    | '/dove-siamo'
    | '/flotta'
    | '/prenota'
    | '/privacy-policy'
    | '/termini-e-condizioni'
    | '/veicoli-commerciali'
    | '/area-clienti/accedi'
    | '/gestionale/analytics'
    | '/gestionale/calendario'
    | '/gestionale/cargos'
    | '/gestionale/clienti'
    | '/gestionale/documenti-legali'
    | '/gestionale/fatture'
    | '/gestionale/partner'
    | '/gestionale/prenotazioni'
    | '/gestionale/tariffe'
    | '/gestionale/utenti'
    | '/gestionale/verbali'
    | '/gestionale'
    | '/area-clienti'
    | '/gestionale/veicoli/$vehicleId'
    | '/api/public/cron/cargos'
    | '/api/public/cron/notifications'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/gestionale/veicoli'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_cliente'
    | '/auth'
    | '/business'
    | '/condizioni-generali'
    | '/contatti'
    | '/cookie-policy'
    | '/dove-siamo'
    | '/flotta'
    | '/prenota'
    | '/privacy-policy'
    | '/termini-e-condizioni'
    | '/veicoli-commerciali'
    | '/_authenticated/gestionale'
    | '/area-clienti/accedi'
    | '/_authenticated/gestionale/analytics'
    | '/_authenticated/gestionale/calendario'
    | '/_authenticated/gestionale/cargos'
    | '/_authenticated/gestionale/clienti'
    | '/_authenticated/gestionale/documenti-legali'
    | '/_authenticated/gestionale/fatture'
    | '/_authenticated/gestionale/partner'
    | '/_authenticated/gestionale/prenotazioni'
    | '/_authenticated/gestionale/tariffe'
    | '/_authenticated/gestionale/utenti'
    | '/_authenticated/gestionale/verbali'
    | '/_authenticated/gestionale/'
    | '/_cliente/area-clienti/'
    | '/_authenticated/gestionale/veicoli/$vehicleId'
    | '/api/public/cron/cargos'
    | '/api/public/cron/notifications'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/gestionale/veicoli/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClienteRoute: typeof ClienteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRoute
  CondizioniGeneraliRoute: typeof CondizioniGeneraliRoute
  ContattiRoute: typeof ContattiRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DoveSiamoRoute: typeof DoveSiamoRoute
  FlottaRoute: typeof FlottaRoute
  PrenotaRoute: typeof PrenotaRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TerminiECondizioniRoute: typeof TerminiECondizioniRoute
  VeicoliCommercialiRoute: typeof VeicoliCommercialiRoute
  AreaClientiAccediRoute: typeof AreaClientiAccediRoute
  ApiPublicCronCargosRoute: typeof ApiPublicCronCargosRoute
  ApiPublicCronNotificationsRoute: typeof ApiPublicCronNotificationsRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cliente': {
      id: '/_cliente'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condizioni-generali': {
      id: '/condizioni-generali'
      path: '/condizioni-generali'
      fullPath: '/condizioni-generali'
      preLoaderRoute: typeof CondizioniGeneraliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dove-siamo': {
      id: '/dove-siamo'
      path: '/dove-siamo'
      fullPath: '/dove-siamo'
      preLoaderRoute: typeof DoveSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flotta': {
      id: '/flotta'
      path: '/flotta'
      fullPath: '/flotta'
      preLoaderRoute: typeof FlottaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prenota': {
      id: '/prenota'
      path: '/prenota'
      fullPath: '/prenota'
      preLoaderRoute: typeof PrenotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termini-e-condizioni': {
      id: '/termini-e-condizioni'
      path: '/termini-e-condizioni'
      fullPath: '/termini-e-condizioni'
      preLoaderRoute: typeof TerminiECondizioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veicoli-commerciali': {
      id: '/veicoli-commerciali'
      path: '/veicoli-commerciali'
      fullPath: '/veicoli-commerciali'
      preLoaderRoute: typeof VeicoliCommercialiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gestionale': {
      id: '/_authenticated/gestionale'
      path: '/gestionale'
      fullPath: '/gestionale'
      preLoaderRoute: typeof AuthenticatedGestionaleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/area-clienti/accedi': {
      id: '/area-clienti/accedi'
      path: '/area-clienti/accedi'
      fullPath: '/area-clienti/accedi'
      preLoaderRoute: typeof AreaClientiAccediRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gestionale/': {
      id: '/_authenticated/gestionale/'
      path: '/'
      fullPath: '/gestionale/'
      preLoaderRoute: typeof AuthenticatedGestionaleIndexRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/analytics': {
      id: '/_authenticated/gestionale/analytics'
      path: '/analytics'
      fullPath: '/gestionale/analytics'
      preLoaderRoute: typeof AuthenticatedGestionaleAnalyticsRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/calendario': {
      id: '/_authenticated/gestionale/calendario'
      path: '/calendario'
      fullPath: '/gestionale/calendario'
      preLoaderRoute: typeof AuthenticatedGestionaleCalendarioRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/cargos': {
      id: '/_authenticated/gestionale/cargos'
      path: '/cargos'
      fullPath: '/gestionale/cargos'
      preLoaderRoute: typeof AuthenticatedGestionaleCargosRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/clienti': {
      id: '/_authenticated/gestionale/clienti'
      path: '/clienti'
      fullPath: '/gestionale/clienti'
      preLoaderRoute: typeof AuthenticatedGestionaleClientiRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/documenti-legali': {
      id: '/_authenticated/gestionale/documenti-legali'
      path: '/documenti-legali'
      fullPath: '/gestionale/documenti-legali'
      preLoaderRoute: typeof AuthenticatedGestionaleDocumentiLegaliRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/fatture': {
      id: '/_authenticated/gestionale/fatture'
      path: '/fatture'
      fullPath: '/gestionale/fatture'
      preLoaderRoute: typeof AuthenticatedGestionaleFattureRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/partner': {
      id: '/_authenticated/gestionale/partner'
      path: '/partner'
      fullPath: '/gestionale/partner'
      preLoaderRoute: typeof AuthenticatedGestionalePartnerRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/prenotazioni': {
      id: '/_authenticated/gestionale/prenotazioni'
      path: '/prenotazioni'
      fullPath: '/gestionale/prenotazioni'
      preLoaderRoute: typeof AuthenticatedGestionalePrenotazioniRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/tariffe': {
      id: '/_authenticated/gestionale/tariffe'
      path: '/tariffe'
      fullPath: '/gestionale/tariffe'
      preLoaderRoute: typeof AuthenticatedGestionaleTariffeRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/utenti': {
      id: '/_authenticated/gestionale/utenti'
      path: '/utenti'
      fullPath: '/gestionale/utenti'
      preLoaderRoute: typeof AuthenticatedGestionaleUtentiRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/verbali': {
      id: '/_authenticated/gestionale/verbali'
      path: '/verbali'
      fullPath: '/gestionale/verbali'
      preLoaderRoute: typeof AuthenticatedGestionaleVerbaliRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_cliente/area-clienti/': {
      id: '/_cliente/area-clienti/'
      path: '/area-clienti'
      fullPath: '/area-clienti/'
      preLoaderRoute: typeof ClienteAreaClientiIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/_authenticated/gestionale/veicoli/': {
      id: '/_authenticated/gestionale/veicoli/'
      path: '/veicoli'
      fullPath: '/gestionale/veicoli/'
      preLoaderRoute: typeof AuthenticatedGestionaleVeicoliIndexRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/veicoli/$vehicleId': {
      id: '/_authenticated/gestionale/veicoli/$vehicleId'
      path: '/veicoli/$vehicleId'
      fullPath: '/gestionale/veicoli/$vehicleId'
      preLoaderRoute: typeof AuthenticatedGestionaleVeicoliVehicleIdRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/api/public/cron/cargos': {
      id: '/api/public/cron/cargos'
      path: '/api/public/cron/cargos'
      fullPath: '/api/public/cron/cargos'
      preLoaderRoute: typeof ApiPublicCronCargosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notifications': {
      id: '/api/public/cron/notifications'
      path: '/api/public/cron/notifications'
      fullPath: '/api/public/cron/notifications'
      preLoaderRoute: typeof ApiPublicCronNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedGestionaleRouteChildren {
  AuthenticatedGestionaleAnalyticsRoute: typeof AuthenticatedGestionaleAnalyticsRoute
  AuthenticatedGestionaleCalendarioRoute: typeof AuthenticatedGestionaleCalendarioRoute
  AuthenticatedGestionaleCargosRoute: typeof AuthenticatedGestionaleCargosRoute
  AuthenticatedGestionaleClientiRoute: typeof AuthenticatedGestionaleClientiRoute
  AuthenticatedGestionaleDocumentiLegaliRoute: typeof AuthenticatedGestionaleDocumentiLegaliRoute
  AuthenticatedGestionaleFattureRoute: typeof AuthenticatedGestionaleFattureRoute
  AuthenticatedGestionalePartnerRoute: typeof AuthenticatedGestionalePartnerRoute
  AuthenticatedGestionalePrenotazioniRoute: typeof AuthenticatedGestionalePrenotazioniRoute
  AuthenticatedGestionaleTariffeRoute: typeof AuthenticatedGestionaleTariffeRoute
  AuthenticatedGestionaleUtentiRoute: typeof AuthenticatedGestionaleUtentiRoute
  AuthenticatedGestionaleVerbaliRoute: typeof AuthenticatedGestionaleVerbaliRoute
  AuthenticatedGestionaleIndexRoute: typeof AuthenticatedGestionaleIndexRoute
  AuthenticatedGestionaleVeicoliVehicleIdRoute: typeof AuthenticatedGestionaleVeicoliVehicleIdRoute
  AuthenticatedGestionaleVeicoliIndexRoute: typeof AuthenticatedGestionaleVeicoliIndexRoute
}

const AuthenticatedGestionaleRouteChildren: AuthenticatedGestionaleRouteChildren =
  {
    AuthenticatedGestionaleAnalyticsRoute:
      AuthenticatedGestionaleAnalyticsRoute,
    AuthenticatedGestionaleCalendarioRoute:
      AuthenticatedGestionaleCalendarioRoute,
    AuthenticatedGestionaleCargosRoute: AuthenticatedGestionaleCargosRoute,
    AuthenticatedGestionaleClientiRoute: AuthenticatedGestionaleClientiRoute,
    AuthenticatedGestionaleDocumentiLegaliRoute:
      AuthenticatedGestionaleDocumentiLegaliRoute,
    AuthenticatedGestionaleFattureRoute: AuthenticatedGestionaleFattureRoute,
    AuthenticatedGestionalePartnerRoute: AuthenticatedGestionalePartnerRoute,
    AuthenticatedGestionalePrenotazioniRoute:
      AuthenticatedGestionalePrenotazioniRoute,
    AuthenticatedGestionaleTariffeRoute: AuthenticatedGestionaleTariffeRoute,
    AuthenticatedGestionaleUtentiRoute: AuthenticatedGestionaleUtentiRoute,
    AuthenticatedGestionaleVerbaliRoute: AuthenticatedGestionaleVerbaliRoute,
    AuthenticatedGestionaleIndexRoute: AuthenticatedGestionaleIndexRoute,
    AuthenticatedGestionaleVeicoliVehicleIdRoute:
      AuthenticatedGestionaleVeicoliVehicleIdRoute,
    AuthenticatedGestionaleVeicoliIndexRoute:
      AuthenticatedGestionaleVeicoliIndexRoute,
  }

const AuthenticatedGestionaleRouteWithChildren =
  AuthenticatedGestionaleRoute._addFileChildren(
    AuthenticatedGestionaleRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGestionaleRoute: typeof AuthenticatedGestionaleRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGestionaleRoute: AuthenticatedGestionaleRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClienteRouteChildren {
  ClienteAreaClientiIndexRoute: typeof ClienteAreaClientiIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteAreaClientiIndexRoute: ClienteAreaClientiIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClienteRoute: ClienteRouteWithChildren,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRoute,
  CondizioniGeneraliRoute: CondizioniGeneraliRoute,
  ContattiRoute: ContattiRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DoveSiamoRoute: DoveSiamoRoute,
  FlottaRoute: FlottaRoute,
  PrenotaRoute: PrenotaRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TerminiECondizioniRoute: TerminiECondizioniRoute,
  VeicoliCommercialiRoute: VeicoliCommercialiRoute,
  AreaClientiAccediRoute: AreaClientiAccediRoute,
  ApiPublicCronCargosRoute: ApiPublicCronCargosRoute,
  ApiPublicCronNotificationsRoute: ApiPublicCronNotificationsRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
